version: '3.7'

services:
  zenn-cli:
    build: .
    container_name: zenn-cli
    working_dir: /zenn/cli
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - '.:/zenn/cli'
    command: bash -c "npm i && npm run preview"
